name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Clean environment
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          rm -f pnpm-lock.yaml

      - name: Install dependencies
        run: |
          pnpm install
          pnpm add -D @rollup/rollup-linux-x64-gnu@4.29.1

      - name: Build project
        env:
          ROLLUP_SKIP_LOAD_NATIVE_PLUGIN: 'true'
        run: pnpm build

      - name: Backup existing deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            timestamp=$(date +%Y%m%d_%H%M%S)
            if [ -d "/var/www/app/dist" ]; then
              mv /var/www/app/dist "/var/www/app/dist_backup_${timestamp}"
            fi

      - name: Copy new build files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist/"
          target: "/var/www/app"

      - name: Configure server and restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            if ! command -v nginx &> /dev/null; then
              apt update && apt install nginx -y
              systemctl enable nginx
            fi

            mkdir -p /var/www/app
            mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled

            chown -R www-data:www-data /var/www/app/dist
            chmod -R 755 /var/www/app/dist

            if [ ! -f "/etc/nginx/sites-available/example.com" ]; then
              echo 'server {
                  listen 80;
                  server_name example.com www.example.com;
                  root /var/www/app/dist;
                  index index.html;
                  location / {
                      try_files $uri $uri/ /index.html;
                  }
                  gzip on;
                  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
              }' > /etc/nginx/sites-available/example.com

              ln -s /etc/nginx/sites-available/example.com /etc/nginx/sites-enabled/
            fi

            if [ ! -f "/etc/letsencrypt/live/example.com/fullchain.pem" ]; then
              apt install -y certbot python3-certbot-nginx
              certbot --nginx --non-interactive --agree-tos \
                --email admin@example.com \
                -d example.com -d www.example.com
            fi

            nginx -t && systemctl restart nginx
